### ISSUE TITLE
[Win10 x64] Game attempts to use 32-bit color

### ISSUE THREAD

**Issue by joehubbert** [ijemafe/rogue-spear-2020#1]
Hi @willroberts - I tried these instructions but still running into issues when the application launches.
I've attached the log file, have you come across this before?

[Rommel.log](https://github.com/willroberts/rogue-spear-2020/files/5793147/Rommel.log)

Thanks,
Joe

**Comment by willroberts** [comment]
Did you set 16-bit color mode on RSConfig.exe and RogueSpear.exe? Looks like it's attempting to use 32-bit color. There are instructions for setting 16-bit color in the README: see step 5 for Rogue Spear and step 4 for Urban Ops.

There may be more info in the DDrawCompat thread for R6 here: https://github.com/narzoul/DDrawCompat/issues/2

You could also try either the [ddraw.dll in this repo](https://github.com/willroberts/rogue-spear-2020/blob/master/ddraw.dll) or an [experimental ddraw.dll from DDrawCompat](https://github.com/narzoul/DDrawCompat/releases/tag/experimental), and see if that helps.

**Comment by joehubbert** [comment]
Thanks for the quick update, it was because I was trying to boot into full screen mode instead of windowed I believe. I got it working in the end with borderless gaming
